const products = [
  {
    id: "tampil1",
    title: "Breathtaking Bromo Adventure",
    category: "group trip",
    location: "Jawa Timur",
    image: "https://drive.google.com/uc?id=1TTZtiRpPO8ciBfmw6DOTDfr6KEJGfObn ",
    date: "2023-12-28",
    price: 2000000,
    description:
      "Ikon alam Indonesia yang menakjubkan, dengan kawahnya yang mmebara dan pemandangan matahari terbit yang memukau diantara lautan pasir. Keindahannya yang megah dan potensi petualangan menjadikannya destinasi yang sangat diminati bagi para pelancong.",
  },
  {
    id: "tampil2",
    title: "Retret Romantis di Parangtritis",
    category: "honeymoon trip",
    location: "Yogyakarta",
    image: "https://drive.google.com/uc?id=14hfWLCZMcp_XAQIlzn5pJoePx34Iq2XH ",
    date: "2023-12-22",
    price: 1800000,
    description:
      "Pantai memukau di Yogyakarta yang memikat dengan garis pantai panjangnya, pasir hitam yang lembut, dan ombak yang menggoda bagi penggemar selancar. Senja yang mempesona di sini melengkapi panorama alam yang menakjubkan, menawarkan pengalaman tak terlupakan bagi pengunjungnya.",
  },
  {
    id: "tampil3",
    title: "Wisata Kawah Putih yang Menawan",
    category: "honeymoon trip",
    location: "Jawa Barat",
    image: "https://drive.google.com/uc?id=1E5a_Mo0P8fmvEQvfIHz_jL_CzLq-IuV8 ",
    date: "2023-12-30",
    price: 2200000,
    description:
      "Lanskap alami menakjubkan di Indonesia yang memikat dengan danau vulkaniknya yang berwarna biru kehijauan yang mempesona. Lingkungan yang mistis dan pemandangan pegunungan yang menakjubkan menjadikan tempat ini sebagai destinasi yang sangat menarik bagi para wisatawan.",
  },
  {
    id: "tampil4",
    title: "Parais Pulau di Nusa Penida",
    category: "honeymoon trip",
    location: "Bali",
    image: "https://drive.google.com/uc?id=1siqB2drYp0GYIoUygNuRZAN5tnYpk7oI ",
    date: "2023-12-15",
    price: 2300000,
    description:
      "Pulau yang menakjubkan di Indonesia dengan pantai-pantai eksotis, terumbu karang yang memukau, dan tebing-tebing yang menjulang tinggi di atas laut biru. Keindahan alamnya yang belum tersentuh menjadikan Nusa Penida surganya para pecinta alam dan penyelam.",
  },
  {
    id: "tampil5",
    title: "Blue Flames of Kawah Ijen",
    category: "group trip",
    location: "Jawa Timur",
    image: "https://drive.google.com/uc?id=1VIPaRGZqZVw1JyjzVKY4Ab3e3iyKLrqQ ",
    date: "2023-12-25",
    price: 2100000,
    description:
      "Tempat yang luar biasa dengan danau asam biru terbesar di dunia serta fenomena api biru yang menakjubkan di malam hari, menarik wisatawan dengan pemandangan alamnya yang unik. Keunikan kawah ini tidak hanya terletak pada panorama alamnya tetapi juga pada kegiatan pertambangan belerang yang dilakukan oleh penduduk setempat di sekitarnya.",
  },
  {
    id: "tampil6",
    title: "Cultural Marvels at Borobudur",
    category: "group trip",
    location: "Jawa Tengah",
    image: "https://drive.google.com/uc?id=1p-Ppd22SiqdM1BLPJofC7G8swfzguurH ",
    date: "2023-12-29",
    price: 1900000,
    description:
      "Keajaiban arsitektur Buddha di Indonesia, dengan struktur monumental yang menakjubkan yang terdiri dari ribuan relief dan stupa, mencerminkan keagungan seni dan spiritualitas pada masa lampau. Sebagai situs warisan dunia UNESCO, Borobudur menarik pengunjung dari seluruh dunia untuk menyaksikan keindahan dan makna budayanya yang mendalam.",
  },
  {
    id: "rec1Honeymoon",
    title: "Romantic Getaway in Bali",
    category: "honeymoon trip",
    location: "Bali",
    image:
      "https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Um9tYW50aWMlMjBHZXRhd2F5JTIwaW4lMjBCYWxpfGVufDB8fDB8fHww",
    date: "2023-09-10",
    price: 2500000,
    description:
      "Bali, dikenal sebagai pulau dewata, menyajikan destinasi romantis yang tak tertandingi. Dengan pantainya yang eksotis, villa-villa mewah di pinggir tebing, dan matahari terbenam yang memukau, Bali menciptakan suasana magis untuk liburan berdua. Nikmati keintiman di antara sawah hijau yang subur atau hadiri ritual keagamaan yang indah untuk pengalaman romantis yang tak terlupakan.",
  },
  {
    id: "rec2Honeymoon",
    title: "Cultural Retreat in Yogyakarta",
    category: "honeymoon trip",
    location: "Yogyakarta",
    image:
      "https://images.unsplash.com/photo-1630214801769-24784bfd2b9c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Q3VsdHVyYWwlMjBSZXRyZWF0JTIwaW4lMjBZb2d5YWthcnRhfGVufDB8fDB8fHww",
    date: "2023-09-15",
    price: 2800000,
    description:
      "Yogyakarta, kota budaya di Jawa, mengundang Anda untuk meresapi kekayaan sejarah dan tradisi Indonesia. Dari istana kerajaan Kraton hingga candi-candi megah seperti Borobudur dan Prambanan, Yogyakarta memancarkan keindahan seni dan arsitektur. Dengan pertunjukan wayang kulit yang mendalam dan kelezatan kuliner khas, ini adalah tempat ideal untuk meresapi kekayaan budaya Indonesia.",
  },
  {
    id: "rec3Honeymoon",
    title: "Island Paradise in Gili Islands",
    category: "honeymoon trip",
    location: "Gili Islands",
    image:
      "https://images.unsplash.com/photo-1587364125669-354c5735dd2d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Z2lsaSUyMGlzbGFuZHN8ZW58MHx8MHx8fDA%3D",
    date: "2023-09-20",
    price: 3000000,
    description:
      "Gili Islands, surganya di Lombok, menawarkan keindahan pulau yang tak terlupakan. Air laut kristal, pasir putih bersih, dan kehidupan bawah laut yang memukau menciptakan surga bagi pecinta pantai dan penyelam. Tanpa kendaraan bermotor, Gili Islands memberikan pengalaman pantai yang damai dan santai, ideal untuk pelarian romantis atau petualangan air yang seru.",
  },
  {
    id: "rec4Honeymoon",
    title: "Luxury Retreat in Ubud",
    category: "honeymoon trip",
    location: "Ubud",
    image:
      "https://images.unsplash.com/photo-1544620463-76ddc1e5d416?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fFVidWR8ZW58MHx8MHx8fDA%3D",
    date: "2023-09-25",
    price: 3200000,
    description:
      "Ubud, pusat seni dan kebudayaan di Bali, memberikan pengalaman mewah yang terpandang. Dikelilingi oleh hutan hijau, resor mewah di Ubud menawarkan kemewahan yang dipadukan dengan keindahan alam. Dengan spa yang mendalam, yoga di tengah sawah, dan kuliner berkualitas tinggi, Ubud memanjakan para tamu dengan keseimbangan sempurna antara kemewahan dan ketenangan.",
  },
  {
    id: "rec5Honeymoon",
    title: "Tropical Paradise in Komodo Island",
    category: "honeymoon trip",
    location: "Komodo Island",
    image: "https://drive.google.com/uc?id=1DB08wuUdHocJsm6Xr8o6wioITabsiTLM ",
    date: "2023-09-30",
    price: 3500000,
    description:
      "Pulau Komodo, yang terkenal dengan naga komodo, menawarkan keindahan alam tropis yang memukau. Dengan pantainya yang mempesona, lautan biru yang jernih, dan keberagaman hayati yang luar biasa, Komodo Island adalah tempat untuk petualangan eksotis. Berkunjunglah ke Taman Nasional Komodo untuk menyaksikan naga komodo dalam habitatnya yang alami atau jelajahi bawah laut yang kaya akan kehidupan laut yang menakjubkan.",
  },
  {
    id: "rec6Honeymoon",
    title: "Sunset Romance in Raja Ampat",
    category: "honeymoon trip",
    location: "Raja Ampat",
    image:
      "https://images.unsplash.com/photo-1561009226-7a820d647a40?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fFN1bnNldCUyMFJvbWFuY2UlMjBpbiUyMFJhamElMjBBbXBhdHxlbnwwfHwwfHx8MA%3D%3D",
    date: "2023-10-05",
    price: 3800000,
    description:
      "Raja Ampat, surganya penyelam, menawarkan keindahan alam bawah laut yang luar biasa dan pemandangan matahari terbenam yang memukau. Dengan terumbu karang yang berwarna-warni dan pulau-pulau terpencil, Raja Ampat adalah destinasi romantis yang sempurna untuk pasangan yang mencari petualangan dan ketenangan di alam.",
  },
  {
    id: "rec7Honeymoon",
    title: "Beach Bliss in Lombok",
    category: "honeymoon trip",
    location: "Lombok",
    image: "https://drive.google.com/uc?id=1GbThOwXMIEEwSQJqy37aoYPoDJm99FFF ",
    date: "2023-10-10",
    price: 3000000,
    description:
      "Lombok, saingan Bali yang tenang, menawarkan keindahan pantai yang belum terjamah. Dengan pasir putih yang lembut dan ombak yang tenang, pantai-pantai di Lombok memberikan suasana damai untuk bersantai. Jelajahi keindahan alam yang asli, termasuk Gunung Rinjani yang megah, dan nikmati keindahan alam yang masih alami.",
  },
  {
    id: "rec8Honeymoon",
    title: "Serenity in Flores",
    category: "honeymoon trip",
    location: "Flores",
    image: "https://drive.google.com/uc?id=1vnXMryVAXPZTyKkatUx0tQJxzkEe4JEl ",
    date: "2023-10-15",
    price: 3200000,
    description:
      "Flores, pulau yang penuh keajaiban alam, memanjakan pengunjung dengan keindahan dan ketenangan. Dari Danau Kelimutu yang unik dengan tiga warna danau hingga pantai-pantai yang indah, Flores menyajikan pengalaman berlibur yang damai dan jauh dari keramaian.",
  },
  {
    id: "rec9Honeymoon",
    title: "Adventure in Bromo",
    category: "honeymoon trip",
    location: "Bromo",
    image: "https://drive.google.com/uc?id=1bF-QSiuGnKRt7p93nUsaY-BAyZ3usHpA ",
    date: "2023-10-20",
    price: 2800000,
    description:
      "Bromo, dengan pesona vulkaniknya, adalah tempat yang sempurna bagi pecinta petualangan. Bersaksilah matahari terbit yang epik di Gunung Bromo, jelajahi lautan pasir yang luas, dan nikmati pemandangan alam yang menakjubkan. Bromo adalah destinasi petualangan yang tidak boleh dilewatkan di Indonesia.",
  },
  {
    id: "rec10Honeymoon",
    title: "Coastal Escape in Belitung",
    category: "honeymoon trip",
    location: "Belitung",
    image: "https://drive.google.com/uc?id=13DKgh9P3DMYM5DuO3IYcIRzbwj57fvhG ",
    date: "2023-10-25",
    price: 3300000,
    description:
      "Belitung, dengan pantai-pantainya yang indah dan bebatuan granit yang unik, menawarkan pelarian pantai yang tenang. Jelajahi pulau ini yang masih alami dengan menyusuri pantai, mengunjungi Pulau Lengkuas yang ikonik, dan menikmati keindahan alam yang mempesona.",
  },
  {
    id: "rec1Concert",
    title: "Java Jazz Festival",
    category: "concert trip",
    location: "Jakarta, Indonesia",
    image: "https://drive.google.com/uc?id=1KLnBUBEAhNomX3r6DP6y8T5tGCbAr1lw ",
    date: "2023-11-01",
    price: 500000,
    description:
      "Java Jazz Festival, acara musik terbesar di Indonesia, memadukan nuansa kota metropolitan dengan kegembiraan musik jazz. Dengan penampilan musisi terkenal dari berbagai genre, festival ini menciptakan pengalaman seni yang tak terlupakan bagi penggemar musik.",
  },
  {
    id: "rec2Concert",
    title: "Ultra Music Festival",
    category: "concert trip",
    location: "Miami, USA",
    image: "https://drive.google.com/uc?id=1LEcQZgVOvod6RTHzmCn7iAtaoiL1Qzb8 ",
    date: "2023-11-10",
    price: 8000000,
    description:
      "Ultra Music Festival, pesta dansa elektronik terkemuka di dunia, menghadirkan kegembiraan musik elektronik di bawah sinar matahari tropis. Dengan panggung megah dan penampilan DJ internasional, festival ini menjadi magnet bagi pecinta musik dansa dari seluruh dunia.",
  },
  {
    id: "rec3Concert",
    title: "Tomorrowland",
    category: "concert trip",
    location: "Boom, Belgium",
    image: "https://drive.google.com/uc?id=1dJWg8QmYY6rENmSt_et0810AqpXE1A6j ",
    date: "2023-11-20",
    price: 10000000,
    description:
      "Tomorrowland, surganya festival musik elektronik, membawa pengunjungnya ke dunia fantasi dengan panggung-panggung yang menakjubkan dan atmosfer penuh energi. Festival ini menghadirkan pengalaman musik yang luar biasa dan menjadi salah satu acara paling dinanti di kalender festival dunia.",
  },
  {
    id: "rec4Concert",
    title: "Burning Man",
    category: "concert trip",
    location: "Black Rock City, USA",
    image: "https://drive.google.com/uc?id=1IClh0SCdFs9f2vMYXC9KRSZoA2CAkbCh ",
    date: "2023-12-01",
    price: 12000000,
    description:
      "Burning Man, perayaan kebudayaan alternatif di tengah padang pasir Nevada, memadukan seni, partisipasi, dan eksplorasi. Dengan instalasi seni yang mengagumkan, festival ini menciptakan komunitas sementara yang unik dan penuh kreativitas.",
  },
  {
    id: "rec5Concert",
    title: "Coachella Valley Music and Arts Festival",
    category: "concert trip",
    location: "Indio, USA",
    image: "https://drive.google.com/uc?id=1CehQNffTnNwFWNPjWBSNoamGQ2RDeEr- ",
    date: "2023-12-10",
    price: 8500000,
    description:
      "Coachella, festival seni dan musik di lembah Coachella, California, menjadi sorotan tahunan dengan penampilan musik live, instalasi seni yang megah, dan atmosfer yang trendi. Festival ini menarik ribuan pengunjung dari seluruh dunia untuk merayakan seni dan musik.",
  },
  {
    id: "rec6Concert",
    title: "Glastonbury Festival",
    category: "concert trip",
    location: "Pilton, UK",
    image: "https://drive.google.com/uc?id=1dqDOMWRZ3lCY4p6hMNCan2wsTbBeSIuA ",
    date: "2023-12-20",
    price: 9500000,
    description:
      "Glastonbury Festival, salah satu festival musik terbesar di dunia, menawarkan pengalaman musik multi-genre di tengah padang rumput Inggris yang indah. Dengan panggung-panggung besar dan atmosfer yang penuh semangat, Glastonbury menjadi tempat berkumpulnya penggemar musik global.",
  },
  {
    id: "rec7Concert",
    title: "Sziget Festival",
    category: "concert trip",
    location: "Budapest, Hungary",
    image: "https://drive.google.com/uc?id=1Qbtfy-Uyd5pJqs1aXYFe2nppLycjv2Ql ",
    date: "2024-01-05",
    price: 7000000,
    description:
      "Sziget Festival, di Pulau Hajógyári di Budapest, menjadi panggung bagi beragam seni pertunjukan dan musik dari seluruh dunia. Festival ini menciptakan atmosfer pesta besar yang dipadukan dengan budaya dan seni dari berbagai belahan dunia.",
  },
  {
    id: "rec8Concert",
    title: "Rock in Rio",
    category: "concert trip",
    location: "Rio de Janeiro, Brazil",
    image: "https://drive.google.com/uc?id=1hVocdhRtyqJoc1JJtQpgJcdHJmfvY8K- ",
    date: "2024-01-15",
    price: 11000000,
    description:
      "Rock in Rio, festival musik mega di Rio de Janeiro, Brasil, menghadirkan penampilan bintang-bintang rock dan pop terkemuka. Dengan panggung megah dan keramaian penggemar, festival ini menjadi magnet bagi pecinta musik dari seluruh Amerika Latin.",
  },
  {
    id: "rec9Concert",
    title: "Wireless Festival",
    category: "concert trip",
    location: "London, UK",
    image: "https://drive.google.com/uc?id=1_GfB4oTp5JNTm2IqvHsSFaRu7frD35jB ",
    date: "2024-01-25",
    price: 6000000,
    description:
      "Wireless Festival, di London, adalah pesta musik urban yang menyajikan penampilan artis hip-hop dan elektronik terkemuka. Dengan atmosfer kota yang hidup, festival ini menjadi destinasi utama bagi pencinta musik urban di Eropa.",
  },
  {
    id: "rec10Concert",
    title: "Sunburn Festival",
    category: "concert trip",
    location: "Goa, India",
    image: "https://drive.google.com/uc?id=1Lumt-5taoQS1bbxaS81DuVngvJswCrtp ",
    date: "2024-02-05",
    price: 5500000,
    description:
      "Sunburn Festival, di Goa, India, adalah festival musik elektronik terbesar di Asia. Dengan penampilan DJ internasional dan pesta pantai yang meriah, festival ini menjadi pusat perhatian bagi penggemar musik dansa di seluruh benua.",
  },
  {
    id: "rec11Concert",
    title: "Electric Daisy Carnival (EDC)",
    category: "concert trip",
    location: "Las Vegas, USA",
    image: "https://drive.google.com/uc?id=1zV6G1Hfn-yNgvP6eBkZfqgmmHkku7HmJ ",
    date: "2024-02-15",
    price: 9000000,
    description:
      "Electric Daisy Carnival (EDC), festival dansa elektronik terkenal di Amerika Utara, menciptakan dunia fantasi penuh cahaya dan suara. Dengan panggung-panggung spektakuler dan pesta di bawah langit malam, EDC menjadi perayaan dansa tak terlupakan.",
  },
  {
    id: "rec12Concert",
    title: "Lollapalooza",
    category: "concert trip",
    location: "Chicago, USA",
    image: "https://drive.google.com/uc?id=1mLQXueuhBzmUv0w8mOjw6T8PrnaaaoJY ",
    date: "2024-02-25",
    price: 7500000,
    description:
      "Lollapalooza, festival musik multi-genre yang berkeliling Amerika Utara, menampilkan pertunjukan musik live, seni pertunjukan, dan makanan lezat. Dengan beragam genre musik yang ditampilkan, Lollapalooza menjadi destinasi musik yang populer bagi penggemar dari segala usia.",
  },
  {
    id: "rec13Concert",
    title: "Exit Festival",
    category: "concert trip",
    location: "Novi Sad, Serbia",
    image: "https://drive.google.com/uc?id=1Hs0ZlgidQTovNjgwxSBu3ZFEJX1e7GRC ",
    date: "2024-03-01",
    price: 6800000,
    description:
      "Exit Festival, di Serbia, merupakan perpaduan musik, seni, dan kemandirian. Festival ini memadukan penampilan musik internasional dengan atmosfer sejarah dan seni yang kreatif, menjadikannya salah satu festival terbaik di Eropa Timur.",
  },
  {
    id: "rec14Concert",
    title: "Pinkpop Festival",
    category: "concert trip",
    location: "Landgraaf, Netherlands",
    image: "https://drive.google.com/uc?id=16vydkwanasGZZABzYypC9ACa_SxS3OnL ",
    date: "2024-03-10",
    price: 7200000,
    description:
      "Pinkpop Festival, festival musik tertua di dunia yang berlokasi di Belanda, mempersembahkan penampilan artis rock dan pop terkemuka. Dengan tradisi panjang dan penggemar yang setia, Pinkpop Festival menjadi salah satu ikon musik Eropa.",
  },
  {
    id: "rec15Concert",
    title: "Summer Sonic Festival",
    category: "concert trip",
    location: "Tokyo, Japan",
    image: "https://drive.google.com/uc?id=1Z41wFF4PrYQpInU6ZJzaxCNqmZnW63c- ",
    date: "2024-03-20",
    price: 8900000,
    description:
      "Summer Sonic Festival, di Jepang, adalah perayaan musik rock dan pop di bawah sinar matahari musim panas. Dengan panggung-panggung yang menghadirkan bintang-bintang internasional, festival ini menjadi destinasi musik utama di Asia.",
  },
  {
    id: "recGroupTrip4",
    title: "Cultural Journey in Jogjakarta",
    category: "group trip",
    location: "Jogjakarta",
    image: "https://drive.google.com/uc?id=13tOqRP82PIw0WeCExFJlKYV5MEwKtz3k ",
    date: "2023-09-30",
    price: 1800000,
    description:
      "Jogjakarta, kota budaya di Jawa, mengajak Anda dalam perjalanan budaya yang mendalam. Dari keraton yang megah hingga seni rupa tradisional, Jogjakarta adalah tempat yang sempurna untuk mengeksplorasi kekayaan budaya Indonesia.",
  },
  {
    id: "recGroupTrip5",
    title: "Trekking Adventure in Rinjani",
    category: "group trip",
    location: "Rinjani",
    image: "https://drive.google.com/uc?id=1v7MiIfROJYtl-ZDhE1Qtsq-IQwTVpyv1 ",
    date: "2023-10-05",
    price: 2000000,
    description:
      "Gunung Rinjani, gunung tertinggi di Lombok, menawarkan petualangan trekking yang menantang. Dengan pemandangan alam yang epik dan danau kawah yang indah, Rinjani adalah destinasi impian bagi para pendaki yang mencari tantangan.",
  },
  {
    id: "recGroupTrip6",
    title: "Beach Retreat in Gili Islands",
    category: "group trip",
    location: "Gili Islands",
    image: "https://drive.google.com/uc?id=1aWP8LzvIGxO-N5C-v0U6N4k1xTiQ69Pm ",
    date: "2023-10-10",
    price: 2200000,
    description:
      "Gili Islands, surga tropis di lepas pantai Lombok, memberikan pengalaman pelarian pantai yang santai. Dengan bungalow-bungalow tepi pantai dan kehidupan bawah laut yang menakjubkan, Gili Islands adalah tempat yang sempurna untuk bersantai dan menikmati keindahan alam.",
  },
  {
    id: "recGroupTrip7",
    title: "Nature Exploration in Borneo",
    category: "group trip",
    location: "Borneo",
    image: "https://drive.google.com/uc?id=18jWJGTWi-CDgMNJ3paOWvjVP7-oDJfYA ",
    date: "2023-10-15",
    price: 2300000,
    description:
      "Borneo, pulau terbesar di Asia, mengundang Anda untuk menjelajahi kekayaan alamnya yang luar biasa. Dari hutan hujan yang lebat hingga orangutan yang langka, Borneo menyajikan pengalaman alam",
  },
  {
    id: "recGroupTrip8",
    title: "Cruise Adventure in Komodo",
    category: "group trip",
    location: "Komodo",
    image: "https://drive.google.com/uc?id=15axh2fAEYYifJFPLwVlI0J9zXYPVi5ha ",
    date: "2023-10-20",
    price: 2800000,
    description:
      "Taman Nasional Komodo, rumah bagi komodo yang unik, menawarkan petualangan pelayaran yang menakjubkan. Dengan pantai-pantai cantik, terumbu karang indah, dan pertemuan dengan komodo, petualangan di Komodo menjadi pengalaman tak terlupakan.",
  },
  {
    id: "recGroupTrip9",
    title: "Culinary Delight in Bandung",
    category: "group trip",
    location: "Bandung",
    image: "https://drive.google.com/uc?id=19CgY_6mfS5DxjfD2BhzH7wnk5eOyuGg_ ",
    date: "2023-10-25",
    price: 1600000,
    description:
      "Bandung, kota kreatif di Jawa Barat, menggoda lidah Anda dengan kekayaan kuliner. Dari makanan jalanan yang lezat hingga restoran kreatif, Bandung adalah surga bagi pecinta kuliner yang ingin menjelajahi cita rasa Indonesia.",
  },
  {
    id: "recGroupTrip10",
    title: "Cultural Immersion in Toraja",
    category: "group trip",
    location: "Toraja",
    image: "https://drive.google.com/uc?id=1Sz0QX3iopdGyixD6CXFwTJhhKkLRe4xA ",
    date: "2023-10-30",
    price: 2100000,
    description:
      "Toraja, di Sulawesi Selatan, mempersembahkan budaya tradisional yang kaya dan unik. Dengan rumah adat tradisional, upacara kematian yang istimewa, dan keindahan alam yang memesona, Toraja menjadi destinasi untuk meresapi keberagaman budaya Indonesia.",
  },
];
